- name: Ensure apt is updated
  shell: apt-get update
  become: true

- name: Install required packages
  shell: apt-get install -y ca-certificates curl
  become: true

- name: Create Docker keyrings directory
  shell: install -m 0755 -d /etc/apt/keyrings
  become: true

- name: Download Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  become: true

- name: Set permissions on Docker GPG key
  shell: chmod a+r /etc/apt/keyrings/docker.asc
  become: true

- name: Add Docker apt repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo ${UBUNTU_CODENAME:-$VERSION_CODENAME}) stable" > /etc/apt/sources.list.d/docker.list
  become: true

- name: Update apt again after adding Docker repo
  shell: apt-get update
  become: true

- name: Install Docker packages
  shell: apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  become: true

- name: Ensure current user is in docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Restart session to apply group change (reboot or re-login required)
  reboot:
    reboot_timeout: 300
  when: docker_group_fix is defined and docker_group_fix | bool
  become: true
