services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.dev
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/domain:/app/packages/domain
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

volumes:
  mongodb_data:
