- name: Install nginx and certbot
  apt:
    name: [nginx, python3-certbot-nginx]
    state: present

- name: Copy NGINX config
  template:
    src: myapp.conf.j2
    dest: /etc/nginx/sites-available/myapp.conf

- name: Enable NGINX site
  file:
    src: /etc/nginx/sites-available/myapp.conf
    dest: /etc/nginx/sites-enabled/myapp.conf
    state: link
    force: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Obtain SSL certificate
  command: certbot --nginx --non-interactive --agree-tos -m {{ ssl_email }} -d {{ domain }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
