- name: Create deployment directory
  file:
    path: "{{ app_dest_dir }}"
    state: directory

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0700"

- name: Copy deploy private key
  copy:
    content: "{{ deploy_key_private_base64 | b64decode }}"
    dest: "/home/{{ app_user }}/.ssh/id_deploy_key"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"

- name: Setup SSH config for GitHub
  copy:
    dest: "/home/{{ app_user }}/.ssh/config"
    content: |
      Host github.com
        HostName github.com
        IdentityFile /home/{{ app_user }}/.ssh/id_deploy_key
        IdentitiesOnly yes
        StrictHostKeyChecking no
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Clone monorepo from GitHub
  git:
    repo: "{{ git_url }}"
    dest: "{{ app_dest_dir }}"
    version: main
    accept_hostkey: yes
    update: yes
  become: yes
  become_user: "{{ app_user }}"

- name: Create .env file from template
  template:
    src: files/env.j2
    dest: "{{ app_dest_dir }}/{{ app_dirname }}/.env"
    mode: "0644"
  vars:
    vite_api_base_url: "{{ vite_api_base_url }}"
    port: "{{ port }}"
    mongo_uri: "{{ mongo_uri }}"

- name: Build Docker images with docker-compose.prod.yml
  command: docker-compose -f docker-compose.prod.yml build
  args:
    chdir: /var/www/myapp
  become: yes
  become_user: "{{ app_user }}"

- name: Start Docker containers with docker-compose.prod.yml
  command: docker-compose -f docker-compose.prod.yml up -d
  args:
    chdir: /var/www/myapp
  become: yes
  become_user: "{{ app_user }}"
