- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP and HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "80"
    - "443"

- name: Allow SSH on custom port {{ ssh_port }}
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Deny default SSH port 22
  ufw:
    rule: deny
    port: 22
    proto: tcp
