version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    networks:
      - myapp-net

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
    networks:
      - myapp-net

  backend:
    build: ./apps/backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - myapp-net

  frontend:
    build: ./apps/frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - myapp-net

volumes:
  mongo_data:

networks:
  myapp-net:
    driver: bridge
