- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Change SSH port to {{ ssh_port }}
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
    backup: yes
    state: present

- name: Create '{{ app_user }}' user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes

- name: Create docker group if it doesn't exist
  group:
    name: docker
    state: present

- name: Add app_user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: yes

- name: Create .ssh directory for {{ app_user }}
  file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0700"

- name: Add authorized SSH key for {{ app_user }}
  copy:
    content: "{{ app_user_ssh_public_key }}"
    dest: "/home/{{ app_user }}/.ssh/authorized_keys"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"

- name: Allow passwordless sudo for {{ app_user }}
  copy:
    dest: "/etc/sudoers.d/{{ app_user }}"
    content: "{{ app_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: yes

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Restart SSH service
  service:
    name: ssh
    state: restarted

- name: Reboot the server and wait a moment
  ansible.builtin.shell: |
    reboot
    sleep 10
  become: yes
  async: 1
  poll: 0
