name: Setup VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_DEPLOY_KEY }}

      - name: Disable strict host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config

      - name: Run Ansible Playbook init
        env:
          ANSIBLE_CONFIG: ./script/setup/ansible.cfg
        run: |
          ansible-playbook scripts/deploy/playbook-init.yml \
            --tags common \
            -i "${{ secrets.VPS_HOST }}," \
            -u ${{ secrets.ROOT_USER }} \
            --extra-vars "
              ssh_port=${{ secrets.SSH_PORT }}
              app_user=${{ secrets.APP_USER }}
              app_user_ssh_public_key='${{ secrets.APP_USER_SSH_PUBLIC_KEY }}'"

      - name: Run Ansible Playbook setup
        env:
          ANSIBLE_CONFIG: ./script/setup/ansible.cfg
        run: |
          ansible-playbook scripts/deploy/playbook-setup.yml \
            --tags common \
            -i "${{ secrets.VPS_HOST }}," \
            -u ${{ secrets.APP_USER }} \
            --extra-vars "
              ansible_port=${{ secrets.SSH_PORT }}
              ssh_port=${{ secrets.SSH_PORT }}
              app_user=${{ secrets.APP_USER }}
              app_user_ssh_public_key='${{ secrets.APP_USER_SSH_PUBLIC_KEY }}'
              domain=${{ secrets.DOMAIN_NAME }}
              ssl_email=${{ secrets.SSL_EMAIL }}
              git_url=${{ secrets.GIT_URL }}"
